name: iOS Build and Review

on:
  push:
    branches: [ main, automation ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-review:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build iOS app
      run: |
        xcodebuild clean build \
          -scheme FloralDesignStudio \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
